# vim: sw=2
name: lupdate

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-qt6:
    name: Qt 6.5.3 / Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      LIBSHV_RUN_LUPDATE: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup CMake
        uses: ./.github/actions/cmake
        with:
          qt_version: 6.5.3
          use_qt6: ON
          modules: qtserialport qtwebsockets

      - name: Refresh translation files
        run: cmake --build '${{github.workspace}}/build' --target update_translations

      - name: Check changes
        run: git diff --exit-code
