# vim: sw=2
name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-qt5:
    name: Run tests / Qt 5.15.2 / Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      CFLAGS: -fsanitize=address,undefined
      CXXFLAGS: -fsanitize=address,undefined
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 5.15.2
          use_qt6: OFF
          modules: ""

      - uses: ./.github/actions/build-and-test

  ubuntu-qt6:
    name: Run tests / Qt 6.5.0 / Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      CFLAGS: -fsanitize=address,undefined
      CXXFLAGS: -fsanitize=address,undefined
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 6.5.0
          use_qt6: ON
          modules: qtserialport qtwebsockets

      - uses: ./.github/actions/build-and-test

  windows:
    name: Run tests / Qt 6.5.0 / Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 6.5.0
          qt_arch: win64_mingw
          use_qt6: ON
          modules: qtserialport qtwebsockets
          additional_cmake_args: -DWITH_LDAP=OFF

      - uses: ./.github/actions/build-and-test

  clang-tidy:
    name: Lint / clang-tidy / Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/run-linter
        with:
          lint_program_with_args: clang-tidy --quiet --warnings-as-errors=*

  clazy:
    name: Lint / clazy / Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/run-linter
        with:
          lint_program_with_args: clazy-standalone --checks=level1,no-fully-qualified-moc-types,no-non-pod-global-static

