# vim: sw=2
name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 5.15.2
          use_qt6: OFF
          modules: ""

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel "$(nproc)"

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -j"$(nproc)"

  build6:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 6.5.0
          use_qt6: ON
          modules: qtserialport qtwebsockets
          additional_cmake_args: -DWITH_LDAP=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel "$(nproc)"

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -j"$(nproc)"
