# vim: sw=2
name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-qt5:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 5.15.2
          use_qt6: OFF
          modules: ""

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel "$(nproc)"

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -j"$(nproc)"

  build-qt6:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/cmake
        with:
          qt_version: 6.5.0
          use_qt6: ON
          modules: qtserialport qtwebsockets

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel "$(nproc)"

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -j"$(nproc)"

  clang-tidy:
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/run-linter
        with:
          lint_program_with_args: clang-tidy --quiet --warnings-as-errors=*

  clazy:
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/run-linter
        with:
          lint_program_with_args: clazy-standalone --checks=level1,no-fully-qualified-moc-types,no-non-pod-global-static

